# Generated by Django 4.2.14 on 2024-07-26 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('order_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestbuy.product')),
            ],
        ),
    ]
