# Generated by Django 4.2.14 on 2024-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy', '0004_alter_customertransaction_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='phone_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
