# Generated by Django 4.2.14 on 2024-08-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy', '0006_license'),
    ]

    operations = [
        migrations.DeleteModel(
            name='License',
        ),
    ]
