# Generated by Django 4.2.14 on 2024-08-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy', '0007_delete_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
