# Generated by Django 4.2.14 on 2024-08-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy', '0008_product_product_cost_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
